{% set name = "pypdb" %}
{% set version = "1.310" %}
{% set sha256 = "aea346e6a10f3400fe56aa89381afcf9dfd533dfc5802d39072e71555c36e16d" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - numpy
    - xmltodict
    - beautifulsoup4
    - requests

test:
  imports:
    - pypdb

about:
    home: http://www.wgilpin.com/pypdb_docs/html/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: A Python toolkit for performing searches with the RCSB Protein Data Bank (PDB) using its XML-based API.
    dev_url: https://github.com/williamgilpin/pypdb

extra:
    recipe-maintainers:
        - tsenapathi
        - moorepants
